import { screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest'
import { refreshSuccessHandler, sysAdminUser } from '../test/msw/handlers/auth'
import { gpuActions, gpuAllocationFixture, gpuAllocationStore, gpuAttachmentOptions, gpuReviewStore } from '../test/msw/handlers/gpu'
import { server } from '../test/msw/server'
import { renderApp } from '../test/render'
import { uuid } from '../test/msw/ids'

beforeEach(() => vi.stubEnv('VITE_GPU_PREVIEW', '1'))
afterEach(() => vi.unstubAllEnvs())
function renderGpu(path = `/console/gpus/${uuid(901)}`) {
  server.use(refreshSuccessHandler('access-user'))
  renderApp(path)
}

describe('GPU allocations', () => {
  test('keeps the service closed by default', async () => {
    vi.stubEnv('VITE_GPU_PREVIEW', '')
    renderGpu('/console/requests/new?kind=GPU')
    await screen.findByRole('heading', { name: '리소스 신청' })
    expect(screen.queryByLabelText('희망 GPU 임대 기간')).not.toBeInTheDocument()
    expect(screen.queryByRole('radio', { name: /^GPU/ })).not.toBeInTheDocument()
    expect(screen.queryByRole('link', { name: /^GPU/ })).not.toBeInTheDocument()
  })
  test('production ignores the preview flag even when it is set', async () => {
    vi.stubEnv('DEV', false)
    renderGpu('/console/requests/new?kind=GPU')
    await screen.findByRole('heading', { name: '리소스 신청' })
    expect(screen.queryByLabelText('희망 GPU 임대 기간')).not.toBeInTheDocument()
    expect(screen.queryByRole('radio', { name: /^GPU/ })).not.toBeInTheDocument()
  })
  test('renders an empty inventory without inventing a GPU', async () => {
    renderGpu('/console/gpus')
    expect(await screen.findByRole('heading', { name: '할당받은 GPU가 없습니다' })).toBeInTheDocument()
  })
  test('requires explicit confirmation and never retries an unavailable VM later', async () => {
    const user = userEvent.setup()
    gpuAllocationStore.push(gpuAllocationFixture())
    gpuAttachmentOptions.push({ vmId: uuid(55), vmName: '다른 노드 VM', nodeId: uuid(8), ready: false, reason: '다른 노드의 VM 이동은 아직 지원하지 않습니다.' })
    renderGpu()
    await user.click(await screen.findByRole('button', { name: 'VM 연결' }))
    const dialog = await screen.findByRole('dialog', { name: 'VM 연결' })
    await user.selectOptions(within(dialog).getByLabelText('연결할 VM'), uuid(55))
    expect(await within(dialog).findByText('다른 노드의 VM 이동은 아직 지원하지 않습니다.')).toBeInTheDocument()
    await user.click(within(dialog).getByRole('checkbox'))
    expect(within(dialog).getByRole('button', { name: 'VM 연결' })).toBeDisabled()
    expect(gpuActions).toHaveLength(0)
    await user.click(within(dialog).getByRole('button', { name: '취소' }))
    expect(gpuActions).toHaveLength(0)
  })
  test('attaches only after selecting a ready VM and confirming its power change', async () => {
    const user = userEvent.setup()
    gpuAllocationStore.push(gpuAllocationFixture())
    gpuAttachmentOptions.push({ vmId: uuid(55), vmName: '학습 VM', nodeId: uuid(9), ready: true, reason: null })
    renderGpu()
    await user.click(await screen.findByRole('button', { name: 'VM 연결' }))
    const dialog = await screen.findByRole('dialog', { name: 'VM 연결' })
    await user.selectOptions(within(dialog).getByLabelText('연결할 VM'), uuid(55))
    expect(within(dialog).getByRole('button', { name: 'VM 연결' })).toBeDisabled()
    expect(gpuActions).toHaveLength(0)
    await user.click(within(dialog).getByRole('checkbox'))
    await user.click(within(dialog).getByRole('button', { name: 'VM 연결' }))
    await waitFor(() => expect(gpuActions).toEqual([{ action: 'attach', body: { vmId: uuid(55), confirmed: true } }]))
    expect(await screen.findByText('VM 연결 요청을 접수했습니다.')).toBeInTheDocument()
  })
  test('detach preserves the lease while return ends the allocation', async () => {
    const user = userEvent.setup()
    gpuAllocationStore.push(gpuAllocationFixture({ connectionStatus: 'ATTACHED', vmId: uuid(55), vmName: '학습 VM' }))
    const originalEnd = gpuAllocationStore[0].leaseEndsAt
    renderGpu()
    await user.click(await screen.findByRole('button', { name: '연결 해제' }))
    const detach = await screen.findByRole('dialog', { name: 'VM 연결 해제' })
    expect(within(detach).getByText('연결을 해제해도 남은 GPU 임대는 유지됩니다.')).toBeInTheDocument()
    await user.click(within(detach).getByRole('checkbox'))
    await user.click(within(detach).getByRole('button', { name: 'VM 연결 해제' }))
    await screen.findByText('VM 연결 해제 요청을 접수했습니다.')
    expect(gpuAllocationStore[0].status).toBe('ALLOCATED')
    expect(gpuAllocationStore[0].leaseEndsAt).toBe(originalEnd)
    await user.click(screen.getByRole('button', { name: 'GPU 반납' }))
    const release = await screen.findByRole('dialog', { name: 'GPU 반납' })
    await user.click(within(release).getByRole('checkbox'))
    await user.click(within(release).getByRole('button', { name: 'GPU 반납' }))
    await screen.findByText('GPU 반납 요청을 접수했습니다.')
    expect(gpuAllocationStore[0].status).toBe('RELEASED')
    expect(gpuActions.map((entry) => entry.action)).toEqual(['detach', 'release'])
  })
  test('viewers cannot connect, extend, return, or manage access', async () => {
    gpuAllocationStore.push(gpuAllocationFixture({ myRole: 'VIEWER', accessManageAllowed: false }))
    renderGpu()
    await screen.findByRole('heading', { name: '학습 GPU' })
    for (const name of ['VM 연결', '임대 연장', 'GPU 반납']) expect(screen.queryByRole('button', { name })).not.toBeInTheDocument()
    expect(screen.queryByRole('link', { name: '접근 권한 관리' })).not.toBeInTheDocument()
    expect(screen.getByText('측정 불가')).toBeInTheDocument()
    expect(screen.queryByText('0%')).not.toBeInTheDocument()
  })
  test('uncertain hardware state keeps destructive user actions hidden', async () => {
    gpuAllocationStore.push(gpuAllocationFixture({ connectionStatus: 'ERROR', error: 'GPU 연결 상태를 확인해 주세요.' }))
    renderGpu()
    await screen.findByText('GPU 연결 상태를 확인해 주세요.')
    expect(screen.queryByRole('button', { name: 'GPU 반납' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: 'VM 연결' })).not.toBeInTheDocument()
  })
  test('low-use review requires a reason and a deliberate reclaim decision', async () => {
    const user = userEvent.setup()
    gpuReviewStore.push({ id: uuid(902), allocationId: uuid(901), allocationName: '학습 GPU', reason: 'LOW_UTILIZATION', evidence: { windowHours: 12, averagePercent: 0, coveragePercent: 100 }, decision: null, decisionReason: null, createdAt: '2026-09-12T00:00:00Z', decidedAt: null })
    server.use(refreshSuccessHandler('access-sys-admin', sysAdminUser))
    renderApp('/admin/gpus')
    await user.click(await screen.findByRole('button', { name: '검토' }))
    const dialog = await screen.findByRole('dialog', { name: 'GPU 회수 검토' })
    expect(gpuActions).toHaveLength(0)
    await user.selectOptions(within(dialog).getByLabelText('검토 결과'), 'RECLAIM')
    await user.type(within(dialog).getByLabelText('결정 사유'), '사용자와 사용 종료 확인')
    expect(within(dialog).getByRole('button', { name: '결정 저장' })).toBeDisabled()
    await user.click(within(dialog).getByRole('checkbox'))
    await user.click(within(dialog).getByRole('button', { name: '결정 저장' }))
    await waitFor(() => expect(gpuActions).toEqual([{ action: 'decision', body: { decision: 'RECLAIM', reason: '사용자와 사용 종료 확인' } }]))
  })
})

test('a priority change requires an operator reason', async () => {
  const user = userEvent.setup()
  gpuAllocationStore.push(gpuAllocationFixture({ status: 'QUEUED', gpu: null, queuePosition: 2, allocatedAt: null, leaseEndsAt: null }))
  server.use(refreshSuccessHandler('access-sys-admin', sysAdminUser))
  renderApp(`/admin/gpus/${uuid(901)}`)
  await user.click(await screen.findByRole('button', { name: '우선순위 변경' }))
  const dialog = await screen.findByRole('dialog', { name: '대기 우선순위 변경' })
  await user.clear(within(dialog).getByLabelText('우선순위'))
  await user.type(within(dialog).getByLabelText('우선순위'), '5')
  expect(within(dialog).getByRole('button', { name: '대기 우선순위 변경' })).toBeDisabled()
  await user.type(within(dialog).getByLabelText('처리 사유'), '수업 시간 배정')
  await user.click(within(dialog).getByRole('button', { name: '대기 우선순위 변경' }))
  await waitFor(() => expect(gpuActions).toEqual([{ action: 'priority', body: { priority: 5, reason: '수업 시간 배정' } }]))
})

test('a measured zero remains different from unavailable utilization', async () => {
  gpuAllocationStore.push(gpuAllocationFixture({ utilizationPercent: 0, sampleObservedAt: new Date().toISOString() }))
  renderGpu()
  expect(await screen.findByText('0%')).toBeInTheDocument()
  expect(screen.queryByText('측정 불가')).not.toBeInTheDocument()
})

test('GPU access changes use the shared grants UI without changing the VM connection', async () => {
  const user = userEvent.setup()
  gpuAllocationStore.push(gpuAllocationFixture({ connectionStatus: 'ATTACHED', vmId: uuid(55), vmName: '학습 VM' }))
  renderGpu(`/console/gpus/${uuid(901)}/access`)
  await screen.findByRole('option', { name: /김철수/ })
  await user.selectOptions(screen.getByLabelText('대상'), uuid(57))
  await user.selectOptions(screen.getByLabelText('등급'), 'EDITOR')
  await user.click(screen.getByRole('button', { name: '부여' }))
  await waitFor(() => expect(gpuActions).toEqual([{ action: 'access-add', body: { granteeType: 'USER', userId: uuid(57), role: 'EDITOR' } }]))
  expect(gpuAllocationStore[0].connectionStatus).toBe('ATTACHED')
  expect(gpuAllocationStore[0].vmId).toBe(uuid(55))
})
